export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const USER_LOGIN_POPUP = 'USER_LOGIN_POPUP'
export const INC_CART = 'INC_CART'
export const DEC_CART = 'DEC_CART'
export const SHADE = 'SHADE'